---
name: last-built

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Dummy'
        required: false
  push:
    branches:
      - "**"
    paths:
      - "*/**"

jobs:
  last-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: gabbersepp/last-successful-build-action@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "master"
          workflow: "always-failing-2"
          fallbackToEarliestSha: ${{inputs.dummy}}
          job: "asda"
          