---
name: last-built

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Dummy'
        required: false
  push:
    branches:
      - "**"
    paths: 
      - "*/**"

jobs:
  last-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: SamhammerAG/last-successful-build-action@issue47
        id: build
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "wurst"
          workflow: "always-failing"
          fallbackToEarliestSha: ${{inputs.dummy}}
          job: "fail"
      - id: echo
        run: |
          SHA=$(echo ${{ steps.build.outputs.sha }})
          echo "sha=${SHA:0:8}"
          