---
name: last-built

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Dummy'
        required: false

jobs:
  last-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: gabbersepp/last-successful-build-action@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "master"
          workflow: "always-failing"
          job: ${{inputs.dummy}}